/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface VotingFactoryInterface extends utils.Interface {
  functions: {
    "allVotingPoll()": FunctionFragment;
    "createVotingPoll(string,address)": FunctionFragment;
    "list_voting_poll(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allVotingPoll"
      | "createVotingPoll"
      | "list_voting_poll"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allVotingPoll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVotingPoll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "list_voting_poll",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allVotingPoll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVotingPoll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "list_voting_poll",
    data: BytesLike
  ): Result;

  events: {};
}

export interface VotingFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allVotingPoll(overrides?: CallOverrides): Promise<[string[]]>;

    createVotingPoll(
      title: string,
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    list_voting_poll(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  allVotingPoll(overrides?: CallOverrides): Promise<string[]>;

  createVotingPoll(
    title: string,
    voter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  list_voting_poll(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    allVotingPoll(overrides?: CallOverrides): Promise<string[]>;

    createVotingPoll(
      title: string,
      voter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    list_voting_poll(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    allVotingPoll(overrides?: CallOverrides): Promise<BigNumber>;

    createVotingPoll(
      title: string,
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    list_voting_poll(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allVotingPoll(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createVotingPoll(
      title: string,
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    list_voting_poll(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
