/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as votingPollFactorySol from "./VotingPollFactory.sol";
export { VotingPoll__factory } from "./VotingPoll__factory";
